# Generated by Django 3.2.13 on 2022-04-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_auto_20220424_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='file',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memo',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
