# Generated by Django 3.2.13 on 2022-04-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_auto_20220424_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='convertable_image/')),
                ('file', models.FileField(blank=True, null=True, upload_to='converted_files/')),
            ],
        ),
        migrations.CreateModel(
            name='FileUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.DeleteModel(
            name='Memo',
        ),
    ]
