# Generated by Django 3.2.13 on 2022-04-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_auto_20220425_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convertfilemodel',
            name='image',
        ),
        migrations.AddField(
            model_name='convertfilemodel',
            name='uploaded_file',
            field=models.FileField(default=1, upload_to='convertable_file/'),
            preserve_default=False,
        ),
    ]
