# Generated by Django 3.2.13 on 2022-04-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0009_alter_fileuploadmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertfilemodel',
            name='image',
            field=models.FileField(default=1, upload_to='convertable_images/'),
            preserve_default=False,
        ),
    ]
