# Generated by Django 3.2.13 on 2022-04-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0010_convertfilemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convertfilemodel',
            name='image',
        ),
    ]
