# Generated by Django 3.2.13 on 2022-04-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0011_remove_convertfilemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertfilemodel',
            name='file',
            field=models.ImageField(upload_to='converted_image/'),
        ),
    ]
