# Generated by Django 3.2.13 on 2022-04-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0012_alter_convertfilemodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertfilemodel',
            name='converted_file',
            field=models.FileField(default=1, upload_to='converted_files/'),
            preserve_default=False,
        ),
    ]
