# Generated by Django 3.2.13 on 2022-04-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0013_convertfilemodel_converted_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
