# Generated by Django 3.2.13 on 2022-04-28 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0014_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
